services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zeit
    ports:
      - 5111:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
